
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author logonrm
 */
public class guiIMC extends javax.swing.JFrame {
        boolean homem=false;
        boolean mulher=false;
        int numeroSexo;
        
        /**
     * Creates new form guiIMC
     */
    public guiIMC() {
        
        initComponents();
       getContentPane().setBackground(new Color(79,143,255));
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Calculo de IMC"); 
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        pesoText = new javax.swing.JTextField();
        alturaText = new javax.swing.JTextField();
        defineSexo = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insira seu Peso");

        jLabel2.setText("Insira sua Altura");

        btnClick.setText("Calcular");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        defineSexo.setMajorTickSpacing(1);
        defineSexo.setMaximum(2);
        defineSexo.setMinorTickSpacing(1);
        defineSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        defineSexo.setExtent(1);
        defineSexo.setValue(1);
        defineSexo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                defineSexoAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                defineSexoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        defineSexo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                defineSexoStateChanged(evt);
            }
        });

        jLabel3.setText("Homem");

        jLabel4.setText("Mulher");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imc.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnClick))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(defineSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(alturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(defineSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addComponent(btnClick)
                .addGap(28, 28, 28)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
       
       
       float peso = Float.parseFloat(pesoText.getText());
       float altura = Float.parseFloat(alturaText.getText());
       
       
       float altura2 = (altura*altura);
       float imc = peso/altura2;
      
       
       
       
       //Homem
       if(numeroSexo==0){
           
          if(imc<20.7){
              JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está abaixo do peso !", "Resultado", JOptionPane.INFORMATION_MESSAGE);
          }
          
          if(imc>20.7 && imc<=26.5){
              JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está no peso normal", "Resultado", JOptionPane.INFORMATION_MESSAGE);
          }
          
          if(imc>26.5 && imc<=27.8){
              JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está ligeiramente acima do peso", "Resultado", JOptionPane.INFORMATION_MESSAGE );
          }
          
          if(imc>27.8 && imc <31.1){
              JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está obeso" , "Resultado", JOptionPane.INFORMATION_MESSAGE);
          }
          
          if(imc>31.1){
              JOptionPane.showMessageDialog(null, "Selecione o seu genero" );
          }
           
       }
       //Não selecionou
       if(numeroSexo==1){
           JOptionPane.showMessageDialog(null, "Selecione o seu genero" );
       }
       //Mulher
       if(numeroSexo==2){
           
           if(imc<19.1){
               JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está abaixo do peso !" , "Resultado", JOptionPane.INFORMATION_MESSAGE);
           }
           
           if(imc>19.1 && imc<=25.8){
                JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está no peso normal" , "Resultado", JOptionPane.INFORMATION_MESSAGE);
           }
           
           if(imc>25.8 && imc<=27.3){
               JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está ligeiramente acima do peso" , "Resultado", JOptionPane.INFORMATION_MESSAGE);
           }
           
           if(imc>27.3 && imc<=32.3){
                JOptionPane.showMessageDialog(null, "O seu IMC é " + imc + " e você está obesa", "Resultado", JOptionPane.INFORMATION_MESSAGE );
           }
           
           if(imc>32.3){
               JOptionPane.showMessageDialog(null, "Selecione o seu genero" );
           }
               
       }
    }//GEN-LAST:event_btnClickActionPerformed

    private void defineSexoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_defineSexoAncestorMoved
        
    }//GEN-LAST:event_defineSexoAncestorMoved

    private void defineSexoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_defineSexoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_defineSexoAncestorAdded

    private void defineSexoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_defineSexoStateChanged
         numeroSexo = defineSexo.getValue();
         
    }//GEN-LAST:event_defineSexoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaText;
    private javax.swing.JButton btnClick;
    private javax.swing.JSlider defineSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pesoText;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
